### ISSUE TITLE
Ruby string interpolation

### ISSUE THREAD

**Issue by PascalPixel** [hejrobin/gloom#11]
<img width="560" alt="screenshot 2017-03-31 13 06 09" src="https://cloud.githubusercontent.com/assets/3094044/24536046/db80f72c-1612-11e7-93ee-a593cf041072.png">
<img width="556" alt="screenshot 2017-03-31 13 06 22" src="https://cloud.githubusercontent.com/assets/3094044/24536045/db8042a0-1612-11e7-9584-f3a81865e70b.png">

When I put variables in strings in haml (ruby) the `#{}` aren't highlighted, I love your theme so much, this is my only issue, how can I fix it?

**Comment by hejrobin** [comment]
This applies to ES6 interpolation aswell, I'll try to push a fix later today (hopefully).

**Comment by PascalPixel** [comment]
Thank you @hejrobin
