### ISSUE TITLE
Add screenshots showing color scheme for different file types

### ISSUE THREAD

**Issue by Gunny123** [hejrobin/gloom#12]
Really dig the theme, but I thought it might be handy to show the color scheme by how it appears when writing HTML, CSS, JS, and other file types. 

I'd happily contribute the screenshots on my Mac if you wish to include them.

**Comment by hejrobin** [comment]
Fixed in https://github.com/hejrobin/gloom/commit/a0c6deb55ac735db2f64e060813e428b01d0c42e
