### ISSUE TITLE
Vim version of gloom color scheme.

### ISSUE THREAD

**Issue by zoharli** [hejrobin/gloom#18]
This is a really good-looking color scheme, but since I'm a vim user, I wonder if there is a plan to make a vim version of this color scheme?

**Comment by hejrobin** [comment]
Currently I'm focusing on [Atom](https://atom.io), but I'm open to port it to `vim` and Sublime in the future.

In the spirit of open source I gladly let people make ports themselves if they reference and/or link to this repo. :)

**Comment by maxgallo** [comment]
+1 on a port to `vim`.
I tried to do it by myself with http://vim.ink/  but the tool doesn't allow you to setup different things :(

**Comment by shelldandy** [comment]
Guys i think you could give https://github.com/jacoborus/estilo a try it can quickly help you make themes for vim airline etc

**Comment by shelldandy** [comment]
Take a look at how this theme (the one i use currently on neovim is made)

https://github.com/mhartington/oceanic-next

Check under the `estilo` folder, everything seems quite readable tbh.

So maybe that could work?

**Comment by hejrobin** [comment]
Feel free to port it as long as you leave credit. I'm not a `vim`-user so it's better to let someone who knows what they're doing port this. 👍

**Comment by shelldandy** [comment]
awesome! i wont port it but hope someone else does 😛
