### ISSUE TITLE
Bug with async Python functions

### ISSUE THREAD

**Issue by jadchaar** [hejrobin/gloom#19]
Big fan of this theme, but today I realized that the theme can get confused when `async` is added in front of `def` when defining a function in Python.

Example:
![screen shot 2017-07-01 at 8 03 44 pm](https://user-images.githubusercontent.com/7388203/27766259-86fdc5bc-5e98-11e7-8ac8-aa2aff4df981.png)

![screen shot 2017-07-01 at 8 03 48 pm](https://user-images.githubusercontent.com/7388203/27766258-86f1599e-5e98-11e7-9b50-da5f64951e3f.png)

**Comment by hejrobin** [comment]
Ah, I'll look in to this, might be an issue with the `python-language` aswell, I'll check this in a few hours when I have a computer nearby. Thanks!

**Comment by hejrobin** [comment]
@jadchaar This is an issue with `atom/langauge-python` referenced here https://github.com/atom/language-python/pull/108, closing as it isn't something I can fix right now
