### ISSUE TITLE
VSCode Version

### ISSUE THREAD

**Issue by apertureless** [hejrobin/gloom#20]
Would ❤️  to see a vscode version of this!

**Comment by hejrobin** [comment]
You are free to port it as long as you give credit.

**Comment by agirton** [comment]
@apertureless I'm sure there are still a few kinks to work through, but here is my port https://github.com/agirton/gloom :heart: Gloom. 

@hejrobin let me know if you would like anything changed as far as where credit goes. Happy to update. Also if you use VS Code let me know if the syntax is off, I noticed VS Code theming is not as clean compared to Atom's.
