### ISSUE TITLE
Syntax highlight broken after update 0.4.2

### ISSUE THREAD

**Issue by robahl** [hejrobin/gloom#3]
Hello!

Since updating to 0.4.2 highlighting is 'plain white'.  I've tried reloading the window/restarting Atom completely, but it does not seem to be working.
![skarmavbild 2017-01-16 kl 17 06 43](https://cloud.githubusercontent.com/assets/979555/21990236/5732a0f8-dc0e-11e6-9619-7f99eaaf2365.png)

Atom v. 1.12.9 macOS 10.12.2

**Comment by hejrobin** [comment]
You'll need Atom 1.13 or newer.
