### ISSUE TITLE
markdown标题

### ISSUE THREAD

**Issue by Val-istar-Guo** [hejrobin/gloom#8]
![image](https://cloud.githubusercontent.com/assets/12405937/23327045/7038061e-fb40-11e6-860d-f90204953565.png)
至少markdown标题（# title）应该有点颜色区分吧

**Comment by hejrobin** [comment]
Please use english, as Google Translate doesn't work 100% every time.

I'm guessing you want improvements to the markdown syntax?

**Comment by Val-istar-Guo** [comment]
please do not mind my poor english.

I think syntax like "# ***" should be use bright color.

like this:

![image](https://cloud.githubusercontent.com/assets/12405937/23329109/da200df8-fb6b-11e6-95c8-7be1d2a259ea.png)

it is easy to read add get the point。

**Comment by hejrobin** [comment]
Great! I will look over Markdown and other languages and make improvements. Thanks!

**Comment by Val-istar-Guo** [comment]
i like your syntax，but Eyes are tired after use a long time.
